name: Node.js CI/CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npx prisma generate
      - run: npm run build

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
        shell: bash

      - name: Print .env file for verification
        run: cat .env

      - name: Reload PM2 with updated environment
        run: |
          pm2 reload BackendAPI --update-env
